language: cpp
compiler: gcc

os:
  - linux
env:
  - PATH=${PWD}

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:

  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90  
  - sudo apt-get install libgtest-dev
before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..
  - cd PATH
script:
  - bash build.sh

notifications:
  email:
    - giliazev.iua@phystech.edu
