language: cpp
compiler: gcc

os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - |
  if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
    CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
    mkdir -p ${DEPS_DIR}/cmake
    travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  fi

script:
  - bash build.sh

notifications:
  email:
    - giliazev.iua@phystech.edu
